<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-06-12 20:48
=======
# Generated by Django 4.0.3 on 2022-06-08 15:00
>>>>>>> main

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
<<<<<<< HEAD
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile-photos/'),
=======
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
>>>>>>> main
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
<<<<<<< HEAD
            field=models.CharField(blank=True, default='', max_length=255),
=======
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
>>>>>>> main
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
=======
>>>>>>> main
    ]
