# Generated by Django 4.0.3 on 2022-06-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('meta_description', models.CharField(max_length=225)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CabinOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('camp', models.CharField(choices=[('SB', 'Suba'), ('LSNG', 'Lasang'), ('BYBYN', 'Baybayon'), ('ZW', 'Zero Waste'), ('GNRL', 'General')], default='GNRL', max_length=5)),
                ('category', models.CharField(choices=[('SCRT', 'Secretariat Cabin'), ('FNC', 'Finance Cabin'), ('WAM', 'Ways and Means Cabin'), ('PBL', 'Publicity Cabin'), ('PRG', 'Programs Cabin'), ('RSR', 'Research Cabin'), ('OTHR', 'Other')], default='OTHR', max_length=5)),
                ('position', models.CharField(choices=[('HD', 'Cabin Head'), ('AHD', 'Assistant Cabin Head'), ('SCRB', 'Scribe'), ('OTHR', 'Other')], default='OTHR', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('camp', models.CharField(choices=[('SB', 'Suba'), ('LSNG', 'Lasang'), ('BYBYN', 'Baybayon'), ('ZW', 'Zero Waste'), ('GNRL', 'General')], default='GNRL', max_length=5)),
                ('position', models.CharField(choices=[('LDR', 'Camp Leader'), ('ALDR', 'Assistant Camp Leader'), ('OTHR', 'Other')], default='OTHR', max_length=5)),
                ('motto', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('SB', 'Suba'), ('LSNG', 'Lasang'), ('BYBYN', 'Baybayon'), ('ZW', 'Zero Waste'), ('GNRL', 'General')], max_length=5, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('tagline', models.CharField(max_length=225)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('category', models.CharField(choices=[('ELCT', 'Election'), ('GAE', 'Grievance and Ethics'), ('OTHR', 'Other')], default='OTHR', max_length=5)),
                ('position', models.CharField(choices=[('CHF', 'Chief Commissioner'), ('CMSR', 'Commissioner'), ('OTHR', 'Other')], default='OTHR', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SR', 'Sponsor'), ('PR', 'Partner'), ('OTHR', 'Other')], default='OTHR', max_length=4)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=50)),
                ('member_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('camp', models.CharField(choices=[('SB', 'Suba'), ('LSNG', 'Lasang'), ('BYBYN', 'Baybayon'), ('ZW', 'Zero Waste'), ('GNRL', 'General')], default='GNRL', max_length=5)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/content/')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=225)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('position', models.CharField(choices=[('PR', 'President'), ('VP', 'Vice-President'), ('SEC', 'Secretary'), ('TRE', 'Treasurer'), ('AUD', 'Auditor'), ('PIO', 'Public Information Officer'), ('OVRS', 'Overseer'), ('DIR', 'Director'), ('OTHR', 'Other')], default='OTHR', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('camp', models.CharField(choices=[('SB', 'Suba'), ('LSNG', 'Lasang'), ('BYBYN', 'Baybayon'), ('ZW', 'Zero Waste'), ('GNRL', 'General')], default='GNRL', max_length=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('contributors', models.ManyToManyField(blank=True, related_name='projects', to='content.contributor')),
                ('gallery', models.ManyToManyField(blank=True, related_name='gallery_projects', to='content.image')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='content.image')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
