# Generated by Django 4.0.3 on 2022-03-23 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_announcement_is_published_event_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=datetime.datetime(2022, 3, 23, 12, 45, 58, 108790, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 12, 46, 8, 212234, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 12, 46, 13, 669694, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 3, 23, 12, 46, 20, 266610, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='content.image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 3, 23, 12, 46, 25, 856297, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=datetime.datetime(2022, 3, 23, 12, 46, 28, 853771, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 12, 46, 30, 919971, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 3, 23, 12, 46, 32, 488607, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
