# Generated by Django 4.0.3 on 2022-03-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_announcement_is_published_event_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumbotron',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.image'),
        ),
    ]
