# Generated by Django 4.0.3 on 2022-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_camppage_name_alter_commissioner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='related_events', to='content.image'),
        ),
    ]
