# Generated by Django 4.0.3 on 2022-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_event_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='camppage',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='gallery_camps', to='content.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='gallery_projects', to='content.image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='gallery_events', to='content.image'),
        ),
    ]
