# Generated by Django 4.0.3 on 2022-03-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_featured_image_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(default=' ')),
                ('featured_image', models.OneToOneField(default=' ', on_delete=django.db.models.deletion.PROTECT, related_name='news', to='content.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
