# Generated by Django 4.0.3 on 2022-03-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='featured_image',
            new_name='image',
        ),
    ]
