# Generated by Django 4.0.3 on 2022-04-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_jumbotron_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SR', 'Sponsor'), ('PR', 'Partner'), ('OTHR', 'Other')], default='OTHR', max_length=4)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to='content.image')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='events', to='content.contributor'),
        ),
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='projects', to='content.contributor'),
        ),
    ]
