# Generated by Django 4.0.3 on 2022-04-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_jumbotron_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinofficer',
            old_name='advocacy',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='campleader',
            old_name='advocacy',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='commissioner',
            old_name='advocacy',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='orgleader',
            old_name='advocacy',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='cabinofficer',
            name='background',
        ),
        migrations.RemoveField(
            model_name='campleader',
            name='background',
        ),
        migrations.RemoveField(
            model_name='commissioner',
            name='background',
        ),
        migrations.RemoveField(
            model_name='orgleader',
            name='background',
        ),
    ]
