# Generated by Django 4.0.3 on 2022-04-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_advocacy_cabinofficer_quote_and_more'),
        ('content', '0007_rename_contributor_event_contributors_and_more'),
    ]

    operations = [
    ]
