# Generated by Django 4.0.3 on 2022-05-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_announcement_options_alter_camppage_options_and_more'),
        ('content', '0010_camppage_tagline'),
    ]

    operations = [
    ]
