# Generated by Django 4.0.3 on 2022-05-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_announcement_meta_description'),
        ('content', '0010_camppage_tagline'),
    ]

    operations = [
    ]
