# Generated by Django 4.0.3 on 2022-05-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_merge_20220503_0141'),
        ('content', '0011_merge_20220509_2149'),
    ]

    operations = [
    ]
