# Generated by Django 4.0.3 on 2022-06-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContainedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PageContainedJumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PageContainedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PageContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('events', models.ManyToManyField(through='page_containers.PageContainedEvent', to='content.event')),
                ('jumbotrons', models.ManyToManyField(through='page_containers.PageContainedJumbotron', to='content.jumbotron')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
