# Generated by Django 4.0.3 on 2022-05-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontainer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
