# Generated by Django 4.0.3 on 2022-06-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_merge_20220509_2149'),
        ('page_containers', '0002_pagecontainedevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontainer',
            name='events',
            field=models.ManyToManyField(through='page_containers.PageContainedEvent', to='content.event'),
        ),
    ]
