# Generated by Django 4.0.3 on 2022-05-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_merge_20220509_2149'),
        ('page_containers', '0003_rename_pagecontainedjumbotrons_pagecontainedjumbotron'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageContainedJumbotrons',
            new_name='PageContainedJumbotron',
        ),
    ]
