# Generated by Django 4.0.3 on 2022-06-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_merge_20220509_2149'),
        ('page_containers', '0003_pagecontainer_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContainedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pagecontainer',
            name='projects',
            field=models.ManyToManyField(through='page_containers.PageContainedProject', to='content.project'),
        ),
        migrations.AddField(
            model_name='pagecontainedproject',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_containers.pagecontainer'),
        ),
        migrations.AddField(
            model_name='pagecontainedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project'),
        ),
        migrations.AddConstraint(
            model_name='pagecontainedproject',
            constraint=models.UniqueConstraint(fields=('container', 'project', 'section_order'), name='unique_container_project_order'),
        ),
        migrations.AddConstraint(
            model_name='pagecontainedproject',
            constraint=models.UniqueConstraint(fields=('container', 'section_order'), name='unique_container_order_for_contained_project'),
        ),
        migrations.AddConstraint(
            model_name='pagecontainedproject',
            constraint=models.UniqueConstraint(fields=('container', 'project'), name='unique_container_project'),
        ),
    ]
