# Generated by Django 4.0.3 on 2022-06-12 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_containers', '0004_pagecontainedproject_pagecontainer_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontainer',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
